### ISSUE TITLE
Unable to build git-po-helper on Mac M1 with Big Sur - ld: framework not found CoreFoundation

### ISSUE THREAD

**Issue by pan93412** [git-l10n/git-po-helper#1]
## Description

I was trying to build `git-po-helper` on my MacBook Pro with Apple M1 processor and it failed with `ld: framework not found CoreFoundation`. I've searched throughout Google and StackOverflow and there is no information about this error in Golang.

### Golang

My `golang` was installed with `brew`. The following is the code I used to install Go compiler:

```bash
$ brew install golang
```

And the following is the Go compiler version I installed.

```bash
$ go version  
go version go1.16.3 darwin/arm64
```

### macOS version

I'm on macOS Big Sur (11.5 Beta, 20G5023d) with its kernel version Darwin 20.6.0.

### `xcode-select --install`

I've installed the toolchain.

```
➜  git-po-helper git:(master) xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

### Some details

- I didn't set up GOPATH, but I heard that it should be configured automatically.

## Logs

```
➜  git-po-helper git:(master) make clean
### Generate version file
### Cleaning git-po-helper
➜  git-po-helper git:(master) make
### Generate version file
VERSION = 0.0.2.6.g2560111
### Generate version file
### Building git-po-helper
GO111MODULE=on go build -ldflags "-X github.com/git-l10n/git-po-helper/version.Version=0.0.2.6.g2560111" -o git-po-helper
# github.com/git-l10n/git-po-helper
/opt/homebrew/Cellar/go/1.16.3/libexec/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: framework not found CoreFoundation
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [git-po-helper] Error 2
```

<img width="842" alt="截圖 2021-05-21 下午3 13 40" src="https://user-images.githubusercontent.com/28441561/119097354-333cd080-ba47-11eb-9b89-14bfad73af47.png">

**Comment by jiangxin** [comment]
I will ask my friend who has masOS on M1 for help.

**Comment by pan93412** [comment]
Should be available to build in go1.17rc2 or later.

**Comment by jiangxin** [comment]
Thanks @pan93412  for noticing this.
