### ISSUE TITLE
Strange warning about gettext version

### ISSUE THREAD

**Issue by jnavila** [git-l10n/git-po-helper#3]
I'm running git-po-helper on a debian testing (gettext version 0.21) and getting the following warning:

```
WARNING cannot find gettext 0.14, and won't run gettext backward compatible test
```

Does it mean that my version of gettext is too advanced and that some "backward compatible" tests cannot be run? Or is it a "bug" about the detection of a version at least v0.14?

Can I do anything to fix/remove this warning?

**Comment by jiangxin** [comment]
This warning message has been updated for disambiguation as follows:

    cannot find gettext 0.14 or 0.15, and won't run backward compatible test on old version of gettext.
    see: https://lore.kernel.org/git/874l8rwrh2.fsf@evledraar.gmail.com/

**Comment by jiangxin** [comment]
> I'm running git-po-helper on a debian testing (gettext version 0.21) and getting the following warning:
> 
> ```
> WARNING cannot find gettext 0.14, and won't run gettext backward compatible test
> ```
> 
> Does it mean that my version of gettext is too advanced and that some "backward compatible" tests cannot be run? Or is it a "bug" about the detection of a version at least v0.14?
> 
> Can I do anything to fix/remove this warning?

See the following link for the reason of introducing old version of gettext for test: 
https://lore.kernel.org/git/874l8rwrh2.fsf@evledraar.gmail.com/

You can install gettext 0.14 in `/opt/gettext/0.14.x` or run `git-po-helper --no-gettext-back-compatible`, or just ignore this warning message.

**Comment by jnavila** [comment]
Oh, i was already at the cause of this issue. Thanks for the link.
