### ISSUE TITLE
Missing prerequisite: wget

### ISSUE THREAD

**Issue by fangyi-zhou** [git-l10n/git-po-helper#5]
Sorry if it may be something very obvious, but I spent quite a bit of time to investigate why tests are failing.

It turns out that my environment doesn't have wget... and due to caching, re-running the test won't show the message 'wget: command not found', which is the error when you run the testsuite the first time without wget.

Afterwards, I got test failures such as 'Dubious, test returned 1 (wstat 256, 0x100)' or 'fail to open repo: cannot find \"po/git.pot\", this command is for git project'.

It appears that https://github.com/git-l10n/git-po-helper/commit/128b61b71e5edfe034ad8aa9a22624829f6a098b intended to generate a warning for failing to verify signature, but also removes the error if download failed.

**Comment by jiangxin** [comment]
Resolved, thanks @fangyi-zhou
